import { AIKnowledgeItem, AISettings, AIChatAnalytics } from '../types';

export const initialAISettings: AISettings = {
  enabled: true,
  assistantNameBn: 'হোলিনেক্স স্মার্ট এআই অ্যাসিস্ট্যান্ট',
  assistantNameEn: 'Holynex Corporate AI Assistant',
  welcomeMessageBn: 'আসসালামু আলাইকুম! হোলিনেক্স গ্রুপে আপনাকে স্বাগতম। ফেয়ার প্রাইস কার্ড, সহজ কিস্তি সুবিধা, পণ্য তালিকা বা ডিলারশিপ সংক্রান্ত যেকোনো তথ্যে আমি আপনাকে সাহায্য করতে পারি। আপনি কীভাবে সাহায্য চান?',
  welcomeMessageEn: 'Welcome to Holynex Group! I am your Corporate AI Assistant. How may I assist you today with our Fair Price Card, Installment Plans, Product Catalog, or Dealership Opportunities?',
  tone: 'professional',
  systemPersonaBn: 'হোলিনেক্স গ্রুপের অফিসিয়াল স্মার্ট এআই অ্যাসিস্ট্যান্ট। মার্জিত, সম্মানিত, ব্যবসায়িক ও সঠিক তথ্যে সমৃদ্ধ সহায়তা প্রদানকারী। কোনো মনগড়া তথ্য না দিয়ে শুধুমাত্র অনুমোদিত তথ্য প্রদান করে।',
  systemPersonaEn: 'Official Corporate AI Representative for Holynex Group. Professional, courteous, strictly factual, and dedicated to transparent consumer services in Bangladesh.',
  fallbackMessageBn: 'দুঃখিত, এই নির্দিষ্ট তথ্যটি তাৎক্ষণিকভাবে যাচাই করা সম্ভব হচ্ছে না। বিস্তারিত নিশ্চিত হতে আমাদের অফিসিয়াল কাস্টমার কেয়ার নম্বরে কল করুন: 01307835260 অথবা হোয়াটসঅ্যাপে যোগাযোগ করুন।',
  fallbackMessageEn: 'I apologize, but this specific information could not be verified automatically. For exact assistance, please contact our Corporate Hotline at 01307835260 or via WhatsApp.',
  supportPhone: '01307835260',
  supportWhatsapp: '01307835260',
  supportEmail: 'contact@holynexgroup.com',
  supportHoursBn: 'শনিবার - বৃহস্পতিবার: সকাল ৯:০০ - রাত ৯:০০',
  supportHoursEn: 'Saturday - Thursday: 9:00 AM - 9:00 PM',
  enableCustomerLookup: true,
  enableDealerLookup: true,
  maxDailyRequestsPerIp: 100,
};

export const initialAIKnowledge: AIKnowledgeItem[] = [
  // General & Corporate
  {
    id: 'kb-corp-01',
    category: 'general',
    questionBn: 'হোলিনেক্স গ্রুপ কী এবং এর মূল উদ্দেশ্য কী?',
    questionEn: 'What is Holynex Group and what is its core mission?',
    answerBn: 'হোলিনেক্স গ্রুপ (Holynex Group) বাংলাদেশের একটি সুপ্রতিষ্ঠিত কর্পোরেট বাণিজ্যিক প্রতিষ্ঠান। আমাদের মূল উদ্দেশ্য হলো মধ্যস্বত্বভোগীদের অতিরিক্ত মুনাফা দূর করে "ফেয়ার প্রাইস কার্ড" এর মাধ্যমে সাধারণ মানুষের কাছে সাশ্রয়ী মূল্যে নিত্যপ্রয়োজনীয় খাদ্যপণ্য এবং সহজ কিস্তিতে ইলেকট্রনিক্স, মোটরসাইকেল ও গৃহস্থালী পণ্য পৌঁছে দেওয়া।',
    answerEn: 'Holynex Group is a premier corporate enterprise in Bangladesh dedicated to empowering citizens by eliminating middleman markups through the Fair Price Card system, offering daily essentials at subsidized rates and home appliances, electronics, and motorcycles on flexible installments.',
    keywords: ['holynex', 'হোলিনেক্স', 'about', 'উদ্দেশ্য', 'কোম্পানি', 'পরিচিতি', 'group', 'mission'],
    active: true,
    priority: 10,
    updatedAt: '2026-03-21T00:00:00Z',
  },
  {
    id: 'kb-corp-02',
    category: 'general',
    questionBn: 'হোলিনেক্স গ্রুপের প্রতিষ্ঠাতা ও বর্তমান পরিচালনা পর্ষদ কারা?',
    questionEn: 'Who are the founders and executive leadership of Holynex Group?',
    answerBn: 'হোলিনেক্স গ্রুপের প্রতিষ্ঠাতা ও স্বপ্নদ্রষ্টা হলেন মরহুম আব্দুল খালেক মোল্লা (Late Abdul Khalek Molla)। বর্তমানে ব্যবস্থাপনা পরিচালক ও প্রধান নির্বাহী কর্মকর্তা (MD & CEO) হিসেবে নেতৃত্ব দিচ্ছেন প্রকৌশলী মোঃ কামরুল হাসান (Engr. Md. Kamrul Hasan)। পরিচালনা পর্ষদের দূরদর্শী নেতৃত্বে প্রতিষ্ঠানটি দেশব্যাপী সেবা সম্প্রসারণ করছে।',
    answerEn: 'Holynex Group was founded by the late visionary entrepreneur Abdul Khalek Molla. The group is currently led by Managing Director & CEO Engr. Md. Kamrul Hasan, guiding sustainable expansion across Bangladesh.',
    keywords: ['chairman', 'ceo', 'চেয়ারম্যান', 'এমডি', 'প্রতিষ্ঠাতা', 'পরিচালক', 'মোল্লা', 'কামরুল হাসান', 'founder', 'leadership'],
    active: true,
    priority: 9,
    updatedAt: '2026-03-21T00:00:00Z',
  },
  {
    id: 'kb-corp-03',
    category: 'contact',
    questionBn: 'প্রধান কার্যালয়ের ঠিকানা এবং যোগাযোগের ফোন নম্বর কী?',
    questionEn: 'What is the head office address and customer support hotline?',
    answerBn: 'হোলিনেক্স গ্রুপ প্রধান কার্যালয়: ৭১২, কমিশনার রোড, জুরাইন, যাত্রাবাড়ী, শ্যামপুর, ঢাকা। অফিসিয়াল হেল্পলাইন ও কাস্টমার কেয়ার: 01307835260। হোয়াটসঅ্যাপ: +8801307835260। ইমেইল: contact@holynexgroup.com। সেবা সময়: শনি-বৃহস্পতি সকাল ৯:০০ থেকে রাত ৯:০০ পর্যন্ত।',
    answerEn: 'Holynex Group Head Office: 712, Commissioner Road, Jurain, Jatrabari, Shyampur, Dhaka, Bangladesh. Official Hotline: 01307835260. WhatsApp: +8801307835260. Email: contact@holynexgroup.com. Hours: Sat-Thu 9:00 AM - 9:00 PM.',
    keywords: ['address', 'phone', 'contact', 'ঠিকানা', 'মোবাইল', 'ফোন', 'অফিস', 'জুরাইন', 'শ্যামপুর', 'যাত্রাবাড়ী', 'হটলাইন', 'location'],
    active: true,
    priority: 10,
    updatedAt: '2026-03-21T00:00:00Z',
  },

  // Fair Price Card System
  {
    id: 'kb-card-01',
    category: 'fair_price_card',
    questionBn: 'ফেয়ার প্রাইস কার্ড (Fair Price Card) কী এবং এর সুবিধা কী?',
    questionEn: 'What is the Fair Price Card and what are its key benefits?',
    answerBn: 'ফেয়ার প্রাইস কার্ড হলো হোলিনেক্স গ্রুপের নিবন্ধিত মেম্বারশিপ কার্ড। কার্ডধারীরা বাজার মূল্যের চেয়ে উল্লেখযোগ্য সাশ্রয়ী পাইকারি ও ভর্তুকি মূল্যে প্রিমিয়াম মিনিকেট চাউল, সয়াবিন তৈল, মসুর ডাল সহ নিত্যপ্রয়োজনীয় পণ্য ক্রয় করতে পারেন। এছাড়াও কার্ডধারীদের জন্য ইলেকট্রনিক্স ও মোটরসাইকেলে অগ্রাধিকার ভিত্তিতে কিস্তি সুবিধা প্রদান করা হয়।',
    answerEn: 'The Fair Price Card is an exclusive customer membership by Holynex Group allowing registered holders to procure essential food items (Miniket rice, edible oils, lentils) at regulated wholesale prices below retail market rates, alongside priority eligibility for consumer installment products.',
    keywords: ['card', 'কার্ড', 'ফেয়ার প্রাইস', 'fair price', 'সুবিধা', 'বেনিফিট', 'membership', 'মেম্বারশিপ'],
    active: true,
    priority: 10,
    updatedAt: '2026-03-21T00:00:00Z',
  },
  {
    id: 'kb-card-02',
    category: 'fair_price_card',
    questionBn: 'ফেয়ার প্রাইস কার্ড কীভাবে তৈরি বা সংগ্রহ করতে হয়?',
    questionEn: 'How can a customer register or obtain a Fair Price Card?',
    answerBn: 'আপনার নিজ এলাকা বা ইউনিয়নের হোলিনেক্স গ্রুপের অনুমোদিত ডিলার পয়েন্ট অথবা স্থানীয় ফিল্ড প্রতিনিধির মাধ্যমে ফেয়ার প্রাইস কার্ডের জন্য নিবন্ধন করতে পারেন। নিবন্ধনের জন্য জাতীয় পরিচয়পত্র (এনআইডি) বা জন্মনিবন্ধনের কপি, পাসপোর্ট সাইজ ছবি এবং নির্ধারিত ৫০০ টাকা ফি জমা দিতে হয়। কার্ড ইস্যুর পর গ্রাহক কার্ড নম্বর (যেমন FPC-2026-XXXX) ও এসএমএস রসিদ পান।',
    answerEn: 'Customers can register for a Fair Price Card through authorized local Holynex dealers or registered area representatives. Requirements include National ID or birth certificate copy, passport-size photograph, and the nominal card fee of 500 BDT. Once issued, an official card code (e.g. FPC-2026-XXXX) and SMS receipt are provided.',
    keywords: ['get card', 'কার্ড পাব কীভাবে', 'কার্ড আবেদন', 'ফি', 'রেজিস্ট্রেশন', 'টাকা', 'card fee', 'issue'],
    active: true,
    priority: 9,
    updatedAt: '2026-03-21T00:00:00Z',
  },
  {
    id: 'kb-card-03',
    category: 'fair_price_card',
    questionBn: 'পণ্য শিডিউল (Product Schedule) কীভাবে কাজ করে?',
    questionEn: 'How does the monthly product schedule work for cardholders?',
    answerBn: 'প্রতিটি ফেয়ার প্রাইস কার্ডধারীর জন্য প্রতি মাসে নির্দিষ্ট কোটায় পণ্য সরবরাহের শিডিউল তৈরি হয়। নির্ধারিত তারিখে (যেমন মাসের ১০ বা ১৫ তারিখ) কার্ডধারী তাদের মনোনীত ডিলার পয়েন্ট বা প্রতিনিধি থেকে চাউল, ডাল ও তৈল নির্ধারিত সাশ্রয়ী মূল্যে গ্রহণ করতে পারেন। প্রতিটি সরবরাহের পর সিস্টেমে তাৎক্ষণিক রসিদ আপডেট হয়।',
    answerEn: 'Each registered cardholder receives an allocated monthly schedule code (e.g. SCH-2026-101) specifying distribution dates, designated dealer pickup points, and subsidized rates for bulk staples like rice and oil.',
    keywords: ['schedule', 'শিডিউল', 'তারিখ', 'কখন পাব', 'কোটা', 'ডেলিভারি তারিখ', 'pickup date', 'allocation'],
    active: true,
    priority: 8,
    updatedAt: '2026-03-21T00:00:00Z',
  },

  // Installments & Down Payment
  {
    id: 'kb-inst-01',
    category: 'installments',
    questionBn: 'হোলিনেক্স গ্রুপের কিস্তি সুবিধার নিয়মাবলী ও ডাউন পেমেন্ট কত?',
    questionEn: 'What are the installment terms and down payment requirements?',
    answerBn: 'আমাদের কিস্তি পদ্ধতি সম্পূর্ণ স্বচ্ছ ও গ্রাহকবান্ধব। পণ্যের মূল্যের মাত্র ২০% থেকে ৩০% প্রাথমিক ডাউন পেমেন্ট প্রদান করে ৬, ১২, ১৮ বা ২৪ মাসের সমান মাসিক কিস্তিতে পণ্য নেওয়া যায়। কোনো গোপন সুদ বা জরিমানা নেই। আবেদনের ২৪ থেকে ৪৮ ঘণ্টার মধ্যে ভেরিফিকেশন সম্পন্ন হয়।',
    answerEn: 'Holynex Group provides transparent installment facilities with an initial down payment of 20% to 30%, repayable in 6, 12, 18, or 24 equal monthly installments. There are zero hidden fees, and applications are typically verified within 24-48 hours.',
    keywords: ['installment', 'কিস্তি', 'ডাউন পেমেন্ট', 'শর্ত', 'মাসিক কিস্তি', 'down payment', 'emi', 'সুদ'],
    active: true,
    priority: 10,
    updatedAt: '2026-03-21T00:00:00Z',
  },
  {
    id: 'kb-inst-02',
    category: 'installments',
    questionBn: 'কিস্তিতে পণ্য নিতে কী কী কাগজপত্র প্রয়োজন?',
    questionEn: 'What documents are required to apply for product installments?',
    answerBn: 'কিস্তি আবেদনের জন্য গ্রাহকের জাতীয় পরিচয়পত্র (এনআইডি) এর কপি, পাসপোর্ট সাইজের ছবি, বর্তমান ঠিকানার ইউটিলিটি বিলের কপি এবং একজন নির্ভরযোগ্য স্থানীয় জামিনদারের (Guarantor) এনআইডি ও ছবি প্রয়োজন হয়। ফেয়ার প্রাইস কার্ডধারীরা অগ্রাধিকার ভিত্তিতে দ্রুততম সময়ে পণ্য বুঝে পান।',
    answerEn: 'Required documentation includes the applicant\'s National ID copy, passport-size photographs, proof of residential address/utility bill, and one local guarantor\'s NID copy. Fair Price Card holders enjoy fast-track verification.',
    keywords: ['documents', 'কাগজপত্র', 'এনআইডি', 'জামিনদার', 'guarantor', 'requirements', 'কিস্তি আবেদন'],
    active: true,
    priority: 9,
    updatedAt: '2026-03-21T00:00:00Z',
  },

  // Products Catalog
  {
    id: 'kb-prod-01',
    category: 'products',
    questionBn: 'হোলিনেক্স গ্রুপে কী কী পণ্য পাওয়া যায়?',
    questionEn: 'What products are available at Holynex Group?',
    answerBn: 'আমাদের পণ্য তালিকায় রয়েছে:\n১. হোম অ্যাপ্লায়েন্স: ইনভার্টার রেফ্রিজারেটর, এয়ার কন্ডিশনার (এসি), ওয়াশিং মেশিন।\n২. ইলেকট্রনিক্স: ৪কে আল্ট্রা এইচডি স্মার্ট এলইডি টিভি, মাইক্রোওয়েভ ওভেন।\n৩. অটোমোবাইল: ১২৫ সিসি প্রিমিয়াম সিটি মোটরসাইকেল ও স্কুটার।\n৪. গ্যাজেটস: ৫জি স্মার্টফোন, ট্যাবলেট।\n৫. ফার্নিচার: সেগুন কাঠের আধুনিক বেডরুম সেট, আলমিরা ও সোফা।\n৬. নিত্যপ্রয়োজনীয় ফেয়ার প্রাইস পণ্য: প্রিমিয়াম মিনিকেট চাউল, খাঁটি সয়াবিন তৈল ও মসুর ডাল।',
    answerEn: 'Holynex catalog includes:\n1. Home Appliances: Inverter Refrigerators, Dual Inverter ACs, Washing Machines.\n2. Consumer Electronics: 4K Ultra HD Smart Android LED TVs.\n3. Vehicles: 125cc City Commuter Motorcycles.\n4. Mobile: 5G Smartphones.\n5. Furniture: Solid Teak Finished Bedroom Sets and Living Furniture.\n6. Daily Essentials: Premium Miniket Rice, Edible Fortified Soybean Oil, and Lentils at fair wholesale rates.',
    keywords: ['products', 'পণ্য', 'টিভি', 'ফ্রিজ', 'চাউল', 'চাল', 'তৈল', 'তেল', 'বাইক', 'মোটরসাইকেল', 'মোবাইল', 'ফার্নিচার', 'catalog'],
    active: true,
    priority: 9,
    updatedAt: '2026-03-21T00:00:00Z',
  },
  {
    id: 'kb-prod-02',
    category: 'products',
    questionBn: 'পণ্যে কোনো অফিসিয়াল ওয়ারেন্টি বা বিক্রয়োত্তর সেবা আছে কি?',
    questionEn: 'Are there official manufacturer warranties and after-sales services?',
    answerBn: 'হ্যাঁ, হোলিনেক্স গ্রুপের প্রতিটি টেকসই পণ্যে শতভাগ জেনুইন ব্র্যান্ড ওয়ারেন্টি অন্তর্ভুক্ত। যেমন রেফ্রিজারেটর কম্প্রেসারে ১০ বছরের ওয়ারেন্টি, ৪কে এলইডি টিভিতে ৪ বছরের প্যানেল ওয়ারেন্টি, এসিতে কপার কনডেন্সার ওয়ারেন্টি এবং ফার্নিচারে ১৫ বছরের ঘুণের নিশ্চয়তা প্রদান করা হয়। অনুমোদিত ডিলার পয়েন্ট ও প্রধান কার্যালয় থেকে সার্বক্ষণিক বিক্রয়োত্তর সেবা দেওয়া হয়।',
    answerEn: 'Yes, 100% genuine manufacturer warranties back all major products: 10-year compressor warranty on refrigerators, 4-year panel warranty on Smart LED TVs, and 15-year borer warranty on furniture, serviced via local authorized dealers.',
    keywords: ['warranty', 'ওয়ারেন্টি', 'গ্যারান্টি', 'সার্ভিসিং', 'বিক্রয়োত্তর', 'after sales'],
    active: true,
    priority: 8,
    updatedAt: '2026-03-21T00:00:00Z',
  },

  // Dealership
  {
    id: 'kb-dlr-01',
    category: 'dealer',
    questionBn: 'হোলিনেক্স গ্রুপের অনুমোদিত ডিলারশিপ কীভাবে নিতে হয়?',
    questionEn: 'How can one become an authorized dealer of Holynex Group?',
    answerBn: 'হোলিনেক্স গ্রুপের অনুমোদিত ডিলারশিপের জন্য সরাসরি আমাদের ওয়েবসাইটের "ডিলার আবেদন" (Dealer Application) পেজ থেকে অনলাইনে আবেদন করতে পারেন। কোনো আলাদা অ্যাকাউন্টের প্রয়োজন নেই। আবেদনপত্রে নাম, পিতার নাম, মাতার নাম, মোবাইল নম্বর, স্থায়ী ও বর্তমান ঠিকানা, ব্যবসা/পেশা, প্রস্তাবিত ডিলার এলাকা এবং আবেদনকারীর পরিষ্কার পাসপোর্ট সাইজ ছবি আপলোড করে চুক্তিপত্রে সম্মতি দিয়ে সাবমিট করলেই আবেদন গৃহীত হয়।',
    answerEn: 'You can apply online directly through our website\'s "Dealer Application" page without requiring any login credentials. Fill out your personal details, designated upazila/thana territory, upload your photograph, and agree to the corporate dealership bylaws to submit.',
    keywords: ['dealer', 'ডিলার', 'ডিলারশিপ', 'আবেদন', 'ব্যবসা', 'ডিলার হতে চাই', 'franchise', 'apply dealer'],
    active: true,
    priority: 10,
    updatedAt: '2026-03-21T00:00:00Z',
  },
  {
    id: 'kb-dlr-02',
    category: 'dealer',
    questionBn: 'ডিলার আবেদনের পর কীভাবে স্ট্যাটাস চেক করতে হয়?',
    questionEn: 'How to track the status of a submitted dealer application?',
    answerBn: 'আবেদন জমা দেওয়ার সাথে সাথে একটি অনন্য অ্যাপ্লিকেশন আইডি (যেমন HNX-2026-000101) তৈরি হয়। আমাদের ওয়েবসাইটের "আবেদন স্ট্যাটাস" (Application Status) মেন্যুতে গিয়ে অ্যাপ্লিকেশন আইডি এবং আপনার নিবন্ধিত মোবাইল নম্বর দিলেই আবেদনের বর্তমান স্ট্যাটাস (Pending, Under Review, Approved) এবং প্রধান কার্যালয়ের বার্তা দেখতে পারবেন।',
    answerEn: 'Upon submission, a unique Application ID (e.g. HNX-2026-000101) is assigned. Visit the "Application Status" tracking page, enter your ID and registered mobile number to view live verification status and official corporate notes.',
    keywords: ['status', 'ট্র্যাকিং', 'স্ট্যাটাস', 'অবস্থা', 'আইডি', 'HNX-2026', 'tracking', 'check status'],
    active: true,
    priority: 10,
    updatedAt: '2026-03-21T00:00:00Z',
  },
  {
    id: 'kb-dlr-03',
    category: 'dealer',
    questionBn: 'ডিলারদের জন্য কী কী সুবিধা ও কমিশন রয়েছে?',
    questionEn: 'What are the business advantages and commissions for authorized dealers?',
    answerBn: 'অনুমোদিত ডিলারদের জন্য নির্ধারিত থানা বা জোনে একচ্ছত্র পণ্য বিপণনের অধিকার থাকে। প্রতিটি ফেয়ার প্রাইস কার্ড অ্যাক্টিভেশনে আকর্ষণীয় কমিশন, কিস্তিতে ইলেকট্রনিক্স ও মোটরসাইকেল সরবরাহে ৫% পর্যন্ত ডিলার কমিশন এবং মাসিক বিক্রয় লক্ষ্যমাত্রা পূরণে বিশেষ বোনাস প্রদান করা হয়। সমস্ত হিসাব কেন্দ্রীয় ডিজিটাল লেজারে রিয়েলটাইমে দৃশ্যমান থাকে।',
    answerEn: 'Authorized dealers enjoy exclusive territory rights, upfront commissions on Fair Price Card enrollments, up to 5% dealer commission on installment product dispatches, plus periodic volume bonuses tracked transparently in the central ledger.',
    keywords: ['commission', 'কমিশন', 'মুনাফা', 'ডিলার লাভ', 'লাভ', 'earnings', 'বোনাস'],
    active: true,
    priority: 9,
    updatedAt: '2026-03-21T00:00:00Z',
  },

  // Security & Human Escalation
  {
    id: 'kb-supp-01',
    category: 'contact',
    questionBn: 'কোনো সমস্যা হলে বা সরাসরি মানুষের সাথে কথা বলতে চাইলে কী করতে হবে?',
    questionEn: 'How can I escalate to a human support agent or speak directly with an officer?',
    answerBn: 'যেকোনো ব্যক্তিগত হিসাব যাচাই, সরাসরি অভিযোগ বা জরুরি পরামর্শের জন্য আপনি সরাসরি আমাদের গ্রাহক সেবা ডেস্কে কল করতে পারেন: 01307835260 (সকাল ৯:০০ - রাত ৯:০০)। এছাড়া হোয়াটসঅ্যাপে সার্বক্ষণিক মেসেজ পাঠাতে পারেন +8801307835260 নম্বরে অথবা যোগাযোগ করুন প্রধান কার্যালয়ে: ৭১২, কমিশনার রোড, জুরাইন, ঢাকা।',
    answerEn: 'For personalized assistance or human escalation, call our Corporate Helpline directly at 01307835260 (9 AM - 9 PM). You can also text via WhatsApp at +8801307835260 or visit our Corporate Office at 712, Commissioner Road, Jurain, Dhaka.',
    keywords: ['human', 'মানুষ', 'সরাসরি কথা', 'এজেন্ট', 'অভিযোগ', 'সাহায্য', 'কাস্টমার কেয়ার', 'help', 'support', 'escalate'],
    active: true,
    priority: 10,
    updatedAt: '2026-03-21T00:00:00Z',
  },
];

export const initialAIChatAnalytics: AIChatAnalytics = {
  totalConversations: 142,
  totalMessages: 618,
  answeredByAI: 485,
  answeredByKnowledgeBase: 112,
  escalatedToHuman: 21,
  banglaPercentage: 86,
  englishPercentage: 14,
  topQueries: [
    { query: 'ফেয়ার প্রাইস কার্ডের সুবিধা কী?', count: 124, category: 'fair_price_card' },
    { query: 'কিস্তিতে ফ্রিজ বা টিভি নেওয়ার নিয়ম', count: 98, category: 'installments' },
    { query: 'ডিলার আবেদনের পদ্ধতি কী?', count: 87, category: 'dealer' },
    { query: 'প্রধান কার্যালয়ের ঠিকানা ও ফোন নম্বর', count: 76, category: 'contact' },
    { query: 'আমার আবেদনের স্ট্যাটাস জানতে চাই', count: 65, category: 'dealer' },
    { query: 'মিনিকেট চাউল ও সয়াবিন তৈলের রেট', count: 52, category: 'products' },
  ],
  recentLogs: [
    {
      id: 'log-ai-01',
      timestamp: '2026-03-21T06:14:00Z',
      query: 'ফেয়ার প্রাইস কার্ডের সুবিধা কী এবং কীভাবে পাব?',
      replySnippet: 'ফেয়ার প্রাইস কার্ড হলো হোলিনেক্স গ্রুপের নিবন্ধিত মেম্বারশিপ কার্ড...',
      lang: 'bn',
      status: 'answered_ai',
      confidence: 'high',
      category: 'fair_price_card',
    },
    {
      id: 'log-ai-02',
      timestamp: '2026-03-21T05:45:00Z',
      query: 'আমার ডিলার আবেদন HNX-2026-000101 এর অবস্থা কী?',
      replySnippet: 'আবেদনকারী: মোঃ কামাল হোসেন (সাভার ডিলার), স্ট্যাটাস: Approved...',
      lang: 'bn',
      status: 'lookup_success',
      confidence: 'high',
      category: 'dealer',
      hasLookup: true,
    },
    {
      id: 'log-ai-03',
      timestamp: '2026-03-21T04:20:00Z',
      query: 'What is the down payment for 43 inch smart TV?',
      replySnippet: 'For the 43" 4K Smart TV (Price: 38,900 BDT), the initial down payment is 7,800 BDT...',
      lang: 'en',
      status: 'answered_ai',
      confidence: 'high',
      category: 'installments',
    },
    {
      id: 'log-ai-04',
      timestamp: '2026-03-20T21:10:00Z',
      query: 'আমি সরাসরি ম্যানেজারের সাথে কথা বলতে চাই',
      replySnippet: 'অবশ্যই, আমাদের প্রধান কার্যালয় হটলাইন 01307835260 নম্বরে কল করুন...',
      lang: 'bn',
      status: 'escalated',
      confidence: 'medium',
      category: 'contact',
    },
  ],
};
